---
title: "Lab 7"
author: "An Bui"
date: "2/21/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(tmap)
library(sf)
library(spatstat)
library(maptools)
library(sp)
library(raster)
library(gstat)
```

#### 1. Raster analysis with Hawaii data in `raster` package

```{r geo tif raster information}
# hawaii
hi_par <- raster("PAR_CLIM_M.tif")
plot(hi_par)

# sst
hi_sst <- raster("SST_LTM.tif")
plot(hi_sst)

# chl A
hi_chl <- raster("CHL_LTM.tif")
plot(hi_chl)

# plot all three side by side
par(mfrow = c(1,3))
plot(hi_par)
plot(hi_sst)
plot(hi_chl)
```

Reproject so that this is in WGS84.

```{r reprojection}
# create a character string to reference
wgs84 <- "+proj=longlat +datum=WGS84 +ellips=WGS84 +no_defs"
# consistency with spaces is IMPORTANT

# reproject raster data
hi_sst_84 <- projectRaster(hi_sst, 
                           # coordinate reference system of choice from character string
                           crs = wgs84, 
                           # method
                           method = "bilinear")
hi_sst_84@crs
# tells you that you're in WGS84

plot(hi_sst_84)
```

Aggregate cells by a factor of 10 using `raster::aggregate` to resample raster data.

```{r aggregate}
sst_rs <- aggregate(hi_sst, fact = 10)
plot(sst_rs)
```


